[2017-11-02 21:44:17 +0100] [14397] [INFO] Starting gunicorn 19.7.1
[2017-11-02 21:44:17 +0100] [14397] [INFO] Listening at: http://0.0.0.0:5000 (14397)
[2017-11-02 21:44:17 +0100] [14397] [INFO] Using worker: eventlet
[2017-11-02 21:44:17 +0100] [14421] [INFO] Booting worker with pid: 14421
[2017-11-02 21:44:22,170] ERROR in app: Exception on /meters/meter_reading [GET]
Traceback (most recent call last):
  File "/home/pi/gastrowalogger_env/lib/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/gastrowalogger_env/lib/python3.4/site-packages/flask/app.py", line 1607, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/home/pi/gastrowalogger_env/lib/python3.4/site-packages/flask/app.py", line 1654, in try_trigger_before_first_request_functions
    func()
  File "/home/pi/gastrowalogger_env/gastrowalogger.py", line 76, in get_sensors
    cur = db.execute("SELECT * FROM sensors WHERE id IN (SELECT * FROM active)")
sqlite3.OperationalError: no such table: sensors
[2017-11-02 21:44:26,515] ERROR in app: Exception on /meters/meter_reading [GET]
Traceback (most recent call last):
  File "/home/pi/gastrowalogger_env/lib/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/gastrowalogger_env/lib/python3.4/site-packages/flask/app.py", line 1607, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/home/pi/gastrowalogger_env/lib/python3.4/site-packages/flask/app.py", line 1654, in try_trigger_before_first_request_functions
    func()
  File "/home/pi/gastrowalogger_env/gastrowalogger.py", line 76, in get_sensors
    cur = db.execute("SELECT * FROM sensors WHERE id IN (SELECT * FROM active)")
sqlite3.OperationalError: no such table: sensors
[2017-11-02 21:45:02,158] ERROR in app: Exception on /meters/meter_reading [GET]
Traceback (most recent call last):
  File "/home/pi/gastrowalogger_env/lib/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/gastrowalogger_env/lib/python3.4/site-packages/flask/app.py", line 1607, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/home/pi/gastrowalogger_env/lib/python3.4/site-packages/flask/app.py", line 1654, in try_trigger_before_first_request_functions
    func()
  File "/home/pi/gastrowalogger_env/gastrowalogger.py", line 76, in get_sensors
    cur = db.execute("SELECT * FROM sensors WHERE id IN (SELECT * FROM active)")
sqlite3.OperationalError: no such table: sensors
[2017-11-02 21:45:41,960] ERROR in app: Exception on /meters/meter_reading [GET]
Traceback (most recent call last):
  File "/home/pi/gastrowalogger_env/lib/python3.4/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/gastrowalogger_env/lib/python3.4/site-packages/flask/app.py", line 1607, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/home/pi/gastrowalogger_env/lib/python3.4/site-packages/flask/app.py", line 1654, in try_trigger_before_first_request_functions
    func()
  File "/home/pi/gastrowalogger_env/gastrowalogger.py", line 76, in get_sensors
    cur = db.execute("SELECT * FROM sensors WHERE id IN (SELECT * FROM active)")
sqlite3.OperationalError: no such table: sensors
[2017-11-02 21:50:25 +0100] [14397] [INFO] Handling signal: term
[2017-11-02 21:50:25 +0100] [14421] [INFO] Worker exiting (pid: 14421)
[2017-11-02 21:50:26 +0100] [14397] [INFO] Shutting down: Master
[2017-11-02 21:50:31 +0100] [16705] [INFO] Starting gunicorn 19.7.1
[2017-11-02 21:50:31 +0100] [16705] [INFO] Listening at: http://0.0.0.0:5000 (16705)
[2017-11-02 21:50:31 +0100] [16705] [INFO] Using worker: eventlet
[2017-11-02 21:50:31 +0100] [16728] [INFO] Booting worker with pid: 16728
[2017-11-02 22:12:37 +0100] [24781] [INFO] Starting gunicorn 19.7.1
[2017-11-02 22:12:37 +0100] [24781] [INFO] Listening at: http://0.0.0.0:5000 (24781)
[2017-11-02 22:12:37 +0100] [24781] [INFO] Using worker: eventlet
[2017-11-02 22:12:37 +0100] [24800] [INFO] Booting worker with pid: 24800
